version: "3.8"
services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: project-container
    ports:
      - "3306:3306" # 포트번호 host:docker 로컬 포트에 도커 포트를 마운트
    volumes:
      # 로컬저장경로:도커저장경로 / 컨테이너 종료 후에도 데이터를 로컬에 저장하여 유지 (로컬 경로변경 가능)
      - ./db/mysql/data:/var/lib/mysql
      # 로컬저장경로:도커저장경로 / 해당 경로에 작성된 DDL을 컨테이너 생성 시 자동실행 (.sql .sh 파일 실행) (로컬 경로변경 가능)
      #- ./db/mysql/init:/docker-entrypoint-initdb.d
    environment: #===== db 환경변수 =====#
      MYSQL_ROOT_PASSWORD: 1234 # root 계정 비밀번호 설정